version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=imagedb
    depends_on:
      - db

  db:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=imagedb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: